version: '3'
services:
  db:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
  api:
    build:
      context: ./api
      dockerfile: containers/development/Dockerfile
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid; bundle install -j3; bin/rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
    environment:
      DATABASE_HOST: 'db'
      REDIS_HOST: 'redis'
      CORS_ALLOWED_ORIGINS: '.*'
    tty: true
    stdin_open: true
  web:
    build:
      context: ./web
      dockerfile: containers/development/Dockerfile
    command: /bin/sh -c "yarn install && yarn dev"
    ports:
      - '8000:8000'
    volumes:
      - ./web:/app
      - /app/node_modules
    # env_file:
    #   - ./web/config/env.development
