AllCops:
  Exclude:
    # 自動生成されるものはチェック対象から除外する
    - db/schema.rb
    - bin/*
    - lib/tasks/auto_annotate_models.rake
    - vendor/bundle/**/* # CircleCI上のディレクトリ
  DisplayCopNames: true
  NewCops: enable

##################### ##################### #####################
# Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

# Use nested module/class definitions instead of compact style.
Style/ClassAndModuleChildren:
  Enabled: false

# Use only ascii symbols in comments.
Style/AsciiComments:
  Enabled: false

# Method has too many lines.
Metrics/MethodLength:
  Max: 12
